name: publish
on: [push]
jobs:
  publish-docker-image-main:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # Running this job only for master branch
    steps:
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & Publish Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          file: ./docker/Dockerfile
          tags: ${{ github.actor }}/steamrt3-pterodactyl:latest    
  publish-docker-image-dev:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev' # Running this job only for master branch
    steps:
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & Publish Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          file: ./docker/Dockerfile
          tags: ${{ github.actor }}/steamrt3-pterodactyl:dev
