name: publish
on: [workflow_dispatch]
jobs:
  publish-docker-image-main:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # Running this job only for master branch
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & Publish Docker image
        run: |
              docker build . -t ghcr.io/1zc/steamrt3-pterodactyl:latest -f docker/Dockerfile
              docker push ghcr.io/1zc/steamrt3-pterodactyl:latest
  publish-docker-image-dev:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev' # Running this job only for master branch
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & Publish Docker image
        run: |
              docker build . -t ghcr.io/1zc/steamrt3-pterodactyl:dev -f docker/Dockerfile
              docker push ghcr.io/1zc/steamrt3-pterodactyl:dev
